### ISSUE TITLE
Nitpicking: Use .byref pragma

### ISSUE THREAD

**Issue by planetis-m** [Clyybber/vulkanim#1]
Currently objects are marked with the ``.bycopy`` pragma which means pass by value on call site. However all wrapped procs? use ptr annotation, which defeats the purpose. Instead replace with ``.byref`` and then:

- ``proc foo(bar: MyObject)`` becames ``void foo(const MyObject *bar)``
- ``proc bar(foo: var MyObject)``, is ``void bar(MyObject *foo)``

# Pros
- Get rid of all the ``addr`` calls, easier to remember and write
- More nim-like api

# Cons
- Will brake the api

(should you say go, I can prepare a Pr)

**Comment by Clyybber** [comment]
One issue is not being able to pass `nil` this way.
