### ISSUE TITLE
Can't assign vkGetInstanceProcAddr to the function pointer from SDL

### ISSUE THREAD

**Issue by michaelnew** [Clyybber/vulkanim#2]
So I'm using [sdl](https://github.com/Vladar4/sdl2_nim) to create a window and then get a pointer to vkGetInstanceProcAddr. Which works fine, but I'm not sure how to assign that to vkGetInstanceProcAddr in a way that vulkanim can use it. If I change line 3389 from this:

`proc vkGetInstanceProcAddr*(instance: VkInstance; pName: cstring): PFNVkvoidfunction {.cdecl, importc.}`  
to this:  
`var vkGetInstanceProcAddr*: proc(instance: VkInstance; pName: cstring): PFNVkvoidfunction {.cdecl.}`  
 
then I can assign the function pointer in my own code like this:  
`vkGetInstanceProcAddr = cast[proc (instance: vulkan.VkInstance, pName: cstring): PFNVkvoidfunction {.cdecl.}](vulkanGetVkGetInstanceProcAddr())`
and everything works fine. But obviously that's not how it's intended to work or I wouldn't have to be changing things manually.

I have a feeling this isn't an oversight and it's more that I just don't know what I'm doing, but any help is very appreciated.

**Comment by Clyybber** [comment]
`proc vkGetInstanceProcAddr*(instance: VkInstance; pName: cstring): PFNVkvoidfunction {.cdecl, importc.}` is intended to be used when you are linking to vulkan statically.
So in your case where you are getting that function from SDL your approach is correct, but you can just store the proc var in your module too (`import vulkanim except vkGetInstanceProcAddr` should work).

You can use the predefined prototypes for the cast btw: `cast[PFNVkgetinstanceprocaddr](vulkanGetVkGetInstanceProcAddr())` :)

**Comment by michaelnew** [comment]
Ahhhh okay. This is starting to make a little more sense to me, thank you :) I had no idea you could exclude a symbol on import like that. Although just declaring it with  
`var vkGetInstanceProcAddr = cast[PFNVkgetinstanceprocaddr](vulkanGetVkGetInstanceProcAddr())`
seems to work fine, even without excluding it on import.

Not sure trying to learn Vulkan and Nim at the same time was a great idea, but I'm a little further along now, so that's something. Thanks again.
